# Generated by Django 3.2.7 on 2021-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
