# Generated by Django 3.2.7 on 2021-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='subtitle',
            field=models.CharField(default='Enter Subtitle', help_text='overwrites the defaults title', max_length=128),
            preserve_default=False,
        ),
    ]
