# Generated by Django 3.2.7 on 2021-09-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogdetailpage_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage_review',
            name='author',
            field=models.CharField(default='Jatin', help_text='overwrites the defaults title', max_length=50),
            preserve_default=False,
        ),
    ]
