# Generated by Django 3.2.7 on 2021-09-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0007_blogdetailpage_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage_review',
            name='author_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
