# Generated by Django 3.2.7 on 2021-09-27 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('blog', '0008_blogdetailpage_review_author_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogListingPage_Review',
            new_name='Review_Lists',
        ),
    ]
