# Generated by Django 3.2.7 on 2021-09-27 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0009_rename_bloglistingpage_review_review_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Details',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customised_title', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('subtitle', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('intro', models.CharField(help_text='overwrites the defaults title', max_length=100)),
                ('author', models.CharField(help_text='overwrites the defaults title', max_length=50)),
                ('date', models.DateField(verbose_name='Post date')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.CharBlock('full_richtext', wagtail.core.blocks.RichTextBlock())), ('simple_richtext', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
                ('author_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PC_Details',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customised_title', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('subtitle', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('intro', models.CharField(help_text='overwrites the defaults title', max_length=100)),
                ('author', models.CharField(help_text='overwrites the defaults title', max_length=50)),
                ('date', models.DateField(verbose_name='Post date')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.CharBlock('full_richtext', wagtail.core.blocks.RichTextBlock())), ('simple_richtext', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
                ('author_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PS4_Details',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customised_title', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('subtitle', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('intro', models.CharField(help_text='overwrites the defaults title', max_length=100)),
                ('author', models.CharField(help_text='overwrites the defaults title', max_length=50)),
                ('date', models.DateField(verbose_name='Post date')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.CharBlock('full_richtext', wagtail.core.blocks.RichTextBlock())), ('simple_richtext', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
                ('author_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Review_Details',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customised_title', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('subtitle', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('intro', models.CharField(help_text='overwrites the defaults title', max_length=100)),
                ('author', models.CharField(help_text='overwrites the defaults title', max_length=50)),
                ('date', models.DateField(verbose_name='Post date')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.CharBlock('full_richtext', wagtail.core.blocks.RichTextBlock())), ('simple_richtext', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
                ('author_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='XBOX_Details',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customised_title', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('subtitle', models.CharField(help_text='overwrites the defaults title', max_length=128)),
                ('intro', models.CharField(help_text='overwrites the defaults title', max_length=100)),
                ('author', models.CharField(help_text='overwrites the defaults title', max_length=50)),
                ('date', models.DateField(verbose_name='Post date')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.CharBlock('full_richtext', wagtail.core.blocks.RichTextBlock())), ('simple_richtext', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
                ('author_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='BlogDetailPage_Review',
            new_name='Hand_Held_Console_Details',
        ),
        migrations.RenameModel(
            old_name='BlogListingPage_Handh_Mobile',
            new_name='Hand_Held_Console_Lists',
        ),
        migrations.RenameModel(
            old_name='BlogListingPage_XBOX',
            new_name='Mobile_Lists',
        ),
        migrations.RenameModel(
            old_name='BlogListingPage_PC',
            new_name='PC_Lists',
        ),
        migrations.RenameModel(
            old_name='BlogListingPage_PS4',
            new_name='PS4_Lists',
        ),
        migrations.RenameModel(
            old_name='BlogListingPage_Handh_Held',
            new_name='XBOX_Lists',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_handheld_console',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_handheld_console',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_mobile',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_mobile',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_pc',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_pc',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_ps4',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_ps4',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_xbox',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage_xbox',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogDetailPage',
        ),
        migrations.DeleteModel(
            name='BlogDetailPage_Handheld_Console',
        ),
        migrations.DeleteModel(
            name='BlogDetailPage_Mobile',
        ),
        migrations.DeleteModel(
            name='BlogDetailPage_PC',
        ),
        migrations.DeleteModel(
            name='BlogDetailPage_PS4',
        ),
        migrations.DeleteModel(
            name='BlogDetailPage_XBOX',
        ),
        migrations.DeleteModel(
            name='BlogListingPage',
        ),
    ]
