# Generated by Django 3.2.7 on 2021-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_review_details_blog_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_details',
            name='quote',
            field=models.CharField(blank=True, help_text='overwrites the defaults title', max_length=100, null=True),
        ),
    ]
