# Generated by Django 3.2.7 on 2021-09-27 18:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_review_details_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_details',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.CharBlock('full_richtext', wagtail.core.blocks.RichTextBlock())), ('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('simple_richtext_2', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
    ]
