# Generated by Django 3.2.7 on 2021-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_review_details_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_details',
            name='categories',
            field=models.CharField(default='Reviews', help_text='overwrites the defaults title', max_length=50),
        ),
    ]
