# Generated by Django 3.2.7 on 2021-09-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_review_details_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_details',
            name='blog_image_2',
        ),
        migrations.RemoveField(
            model_name='review_details',
            name='subtitle',
        ),
    ]
