# Generated by Django 3.2.7 on 2021-09-30 15:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210930_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_details',
            old_name='blog_image',
            new_name='Featured_image',
        ),
        migrations.AlterField(
            model_name='review_details',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('blog_image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
    ]
