# Generated by Django 3.2.7 on 2021-09-30 16:04

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210930_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand_held_console_details',
            old_name='blog_image',
            new_name='Featured_image',
        ),
        migrations.RenameField(
            model_name='mobile_details',
            old_name='blog_image',
            new_name='Featured_image',
        ),
        migrations.RenameField(
            model_name='pc_details',
            old_name='blog_image',
            new_name='Featured_image',
        ),
        migrations.RenameField(
            model_name='ps4_details',
            old_name='blog_image',
            new_name='Featured_image',
        ),
        migrations.RenameField(
            model_name='xbox_details',
            old_name='blog_image',
            new_name='Featured_image',
        ),
        migrations.RemoveField(
            model_name='hand_held_console_details',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='mobile_details',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='pc_details',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='ps4_details',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='xbox_details',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='hand_held_console_details',
            name='categories',
            field=models.CharField(default='Reviews', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AddField(
            model_name='hand_held_console_details',
            name='quote',
            field=models.CharField(blank=True, help_text='overwrites the defaults title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_details',
            name='categories',
            field=models.CharField(default='Reviews', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AddField(
            model_name='mobile_details',
            name='quote',
            field=models.CharField(blank=True, help_text='overwrites the defaults title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_details',
            name='categories',
            field=models.CharField(default='Reviews', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AddField(
            model_name='pc_details',
            name='quote',
            field=models.CharField(blank=True, help_text='overwrites the defaults title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ps4_details',
            name='categories',
            field=models.CharField(default='Reviews', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AddField(
            model_name='ps4_details',
            name='quote',
            field=models.CharField(blank=True, help_text='overwrites the defaults title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xbox_details',
            name='categories',
            field=models.CharField(default='Reviews', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AddField(
            model_name='xbox_details',
            name='quote',
            field=models.CharField(blank=True, help_text='overwrites the defaults title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hand_held_console_details',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('blog_image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile_details',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('blog_image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_details',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('blog_image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ps4_details',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('blog_image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbox_details',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.RichTextBlock()), ('Blog_image', wagtail.core.blocks.StructBlock([('blog_image', wagtail.images.blocks.ImageChooserBlock(help_text='Image the automagically cropped to 786px by 552px'))]))], blank=True, null=True),
        ),
    ]
