# Generated by Django 3.2.7 on 2021-09-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210930_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand_held_console_details',
            name='categories',
            field=models.CharField(default='Hand Held Console', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile_details',
            name='categories',
            field=models.CharField(default='Mobile', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AlterField(
            model_name='pc_details',
            name='categories',
            field=models.CharField(default='PC', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AlterField(
            model_name='ps4_details',
            name='categories',
            field=models.CharField(default='PS4', help_text='overwrites the defaults title', max_length=50),
        ),
        migrations.AlterField(
            model_name='xbox_details',
            name='categories',
            field=models.CharField(default='XBOX', help_text='overwrites the defaults title', max_length=50),
        ),
    ]
