# Generated by Django 3.2.7 on 2021-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210930_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand_held_console_details',
            name='keywords',
            field=models.CharField(help_text='Keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_details',
            name='keywords',
            field=models.CharField(help_text='Keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_details',
            name='keywords',
            field=models.CharField(help_text='Keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ps4_details',
            name='keywords',
            field=models.CharField(help_text='Keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review_details',
            name='keywords',
            field=models.CharField(help_text='Keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xbox_details',
            name='keywords',
            field=models.CharField(help_text='Keywords', max_length=100, null=True),
        ),
    ]
