# Generated by Django 3.2.7 on 2021-10-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0027_postpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
